manifest_version = 2
id = "taiga"
name = "Taiga"
version = "0.1.0~ynh1"
license = "AGPL-3.0"
description.en = "Agile project management platform (YunoHost package)"
description.fr = "Plateforme de gestion de projet agile (paquet YunoHost)"
url = "https://taiga.io/"
multi_instance = false

[[maintainers]]
name = "Your Name"
email = "your@email.com"

[[requirements]]
type = "ynh_version"
version = ">= 11.0.0"

services = ["nginx", "postgresql", "redis", "rabbitmq"]

[[arguments]]
name = "domain"
type = "domain"
ask.en = "On which domain should Taiga be installed?"
ask.fr = "Sur quel domaine installer Taiga ?"
example = "domain.tld"

[[arguments]]
name = "path"
type = "path"
ask.en = "On which path should Taiga be accessible?"
ask.fr = "À quel chemin Taiga doit-il être accessible ?"
example = "/taiga"
